import React, { useState, useEffect, useRef } from 'react';
import { Mic, MicOff, Send, MessageSquare, Loader2, Bot, User, FileText, Paperclip, X, Download, FileDown } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { sendMessage, Attachment, SlideDeckData } from './gemini';
import { useLiveAPI } from './useLiveAPI';
import { Content } from '@google/genai';
import pptxgen from 'pptxgenjs';
import { jsPDF } from 'jspdf';
import { SYSTEM_INSTRUCTION } from './knowledge_base';

export default function App() {
  const [messages, setMessages] = useState<{ role: string, text: string }[]>([]);
  const [context, setContext] = useState<Content[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [attachments, setAttachments] = useState<Attachment[]>([]);
  const [exportMenuOpen, setExportMenuOpen] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const bottomRef = useRef<HTMLDivElement>(null);

  const { connect: connectLive, disconnect: disconnectLive, isConnected: isLiveConnected, isConnecting: isLiveConnecting, transcript } = useLiveAPI();

  useEffect(() => {
    // Initial greeting
    setMessages([{ role: 'model', text: 'Hello! I am the PCFT AI Digital Assistant. How can I help you understand your rights, benefits, or the negotiated agreement today?' }]);
  }, []);

  useEffect(() => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, transcript]);

  const processFile = (file: File) => {
    const validImageTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'];
    const validDocTypes = ['application/pdf', 'text/plain'];
    if (!validImageTypes.includes(file.type) && !validDocTypes.includes(file.type)) {
      alert("Unsupported file format. Please upload an image, PDF, or text file.");
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const dataUrl = e.target?.result as string;
      const base64 = dataUrl.split(',')[1];
      setAttachments(prev => [...prev, { mimeType: file.type, base64, name: file.name }]);
    };
    reader.readAsDataURL(file);
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    if (e.clipboardData.files && e.clipboardData.files.length > 0) {
      Array.from(e.clipboardData.files).forEach(processFile);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      Array.from(e.target.files).forEach(processFile);
    }
  };

  const generateSlideDeck = (data: SlideDeckData) => {
    const pres = new pptxgen();
    pres.layout = 'LAYOUT_16x9';
    pres.author = 'PCFT Assistant';
    pres.company = 'PCFT';

    const titleSlide = pres.addSlide();
    titleSlide.addText(data.title, { x: 1, y: 2, w: '80%', h: 1, fontSize: 36, bold: true, color: '003366', align: 'center' });
    titleSlide.addText('Generated by PCFT Assistant', { x: 1, y: 3, w: '80%', h: 1, fontSize: 18, color: '666666', align: 'center' });

    data.slides.forEach(slide => {
      const s = pres.addSlide();
      s.addText(slide.title, { x: 0.5, y: 0.5, w: '90%', h: 1, fontSize: 28, bold: true, color: '003366' });
      s.addText(slide.bullets.map(b => ({ text: b })), {
        x: 0.5, y: 1.8, w: '90%', h: 4, 
        bullet: { type: 'bullet' }, fontSize: 18, align: 'left', color: '333333'
      });
    });

    pres.writeFile({ fileName: `PCFT_Presentation_${Date.now()}.pptx` });
  };

  const handleSend = async (e?: React.FormEvent) => {
    e?.preventDefault();
    if ((!inputValue.trim() && attachments.length === 0) || isLoading) return;

    const userMessage = inputValue.trim();
    const currentAttachments = [...attachments];
    setInputValue('');
    setAttachments([]);
    
    let msgDisplay = userMessage;
    if (currentAttachments.length > 0) {
      msgDisplay += `\n*[Attached ${currentAttachments.length} file(s)]*`;
    }
    setMessages(prev => [...prev, { role: 'user', text: msgDisplay }]);
    setIsLoading(true);
    setError('');

    try {
      const { text, newContext, slideDeck } = await sendMessage(context, userMessage, currentAttachments);
      setMessages(prev => [...prev, { role: 'model', text }]);
      setContext(newContext);
      
      if (slideDeck) {
        generateSlideDeck(slideDeck);
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Failed to get a response.');
      setMessages(prev => [...prev, { role: 'system', text: 'Error: ' + (err.message || 'Failed to get a response.') }]);
    } finally {
      setIsLoading(false);
    }
  };

  const exportChat = (format: 'txt' | 'md' | 'word' | 'pdf') => {
    setExportMenuOpen(false);
    let content = "# PCFT Digital Assistant Chat Export\n\n";
    messages.filter(m => m.role !== 'system').forEach(msg => {
      content += `**${msg.role === 'user' ? 'You' : 'Assistant'}**:\n${msg.text}\n\n`;
    });

    if (format === 'txt' || format === 'md') {
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `PCFT_Chat_${Date.now()}.${format}`;
      a.click();
    } else if (format === 'word') {
      const htmlHeader = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>PCFT Chat Export</title></head><body>";
      const htmlFooter = "</body></html>";
      let htmlContent = "<h1>PCFT Digital Assistant Chat Export</h1>";
      messages.filter(m => m.role !== 'system').forEach(msg => {
        htmlContent += `<h3>${msg.role === 'user' ? 'You' : 'Assistant'}</h3><p>${msg.text.replace(/\\n/g, '<br/>')}</p>`;
      });
      const blob = new Blob(['\ufeff', htmlHeader + htmlContent + htmlFooter], { type: 'application/msword;charset=utf-8' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `PCFT_Chat_${Date.now()}.doc`;
      a.click();
    } else if (format === 'pdf') {
      const doc = new jsPDF();
      doc.setFontSize(16);
      doc.text("PCFT Chat Export", 10, 10);
      doc.setFontSize(11);
      let y = 20;
      messages.filter(m => m.role !== 'system').forEach(msg => {
        const splitText = doc.splitTextToSize(`${msg.role === 'user' ? 'You' : 'Assistant'}:\n${msg.text}`, 180);
        if (y + splitText.length * 5 > 280) {
          doc.addPage();
          y = 10;
        }
        doc.text(splitText, 10, y);
        y += splitText.length * 5 + 5;
      });
      doc.save(`PCFT_Chat_${Date.now()}.pdf`);
    }
  };

  const downloadReferenceDoc = (docTitle: string) => {
    // Extract document section from SYSTEM_INSTRUCTION
    const docRegex = new RegExp(`### DOCUMENT \\d+: ${docTitle}([\\s\\S]*?)(?=### DOCUMENT|$)`);
    const match = SYSTEM_INSTRUCTION.match(docRegex);
    const content = match ? match[1].trim() : "Document content not found.";
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${docTitle.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
    a.click();
  };

  const toggleLive = () => {
    if (isLiveConnected || isLiveConnecting) {
      disconnectLive();
    } else {
      connectLive();
    }
  };

  return (
    <div className="flex flex-col h-screen bg-slate-50 font-sans text-slate-800">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-slate-200 px-6 py-4 flex items-center justify-between z-10 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-white shadow-md">
            <Bot size={24} />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900 leading-none">PCFT Digital Assistant</h1>
            <p className="text-sm text-slate-500 font-medium">Pierce College Federation of Teachers</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => {
              const key = prompt('Enter your Gemini API Key (saved locally):');
              if (key) {
                localStorage.setItem('gemini_api_key', key);
                alert('API Key saved to your browser!');
                window.location.reload();
              }
            }}
            className="text-sm px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors border border-slate-200"
          >
            Set API Key
          </button>
          <div className="relative">
            <button
              onClick={() => setExportMenuOpen(!exportMenuOpen)}
              className="flex items-center gap-2 px-4 py-2 rounded-full font-medium transition-all shadow-sm bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300 text-slate-700"
            >
              <FileDown size={18} />
              <span className="hidden sm:inline">Export Chat</span>
            </button>
            <AnimatePresence>
              {exportMenuOpen && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 10 }}
                  className="absolute right-0 mt-2 w-48 bg-white rounded-xl shadow-lg border border-slate-100 overflow-hidden z-20"
                >
                  <div className="flex flex-col py-1">
                    <button onClick={() => exportChat('md')} className="px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 hover:text-blue-600">Markdown (.md)</button>
                    <button onClick={() => exportChat('txt')} className="px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 hover:text-blue-600">Text (.txt)</button>
                    <button onClick={() => exportChat('word')} className="px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 hover:text-blue-600">Word (.doc)</button>
                    <button onClick={() => exportChat('pdf')} className="px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 hover:text-blue-600">PDF Document</button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
          <button
            onClick={toggleLive}
            disabled={isLiveConnecting}
            className={`flex items-center gap-2 px-4 py-2 rounded-full font-medium transition-all shadow-sm ${
              isLiveConnected 
              ? 'bg-red-50 text-red-600 border border-red-200 hover:bg-red-100'
              : 'bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300'
            }`}
          >
            {isLiveConnecting ? (
              <Loader2 size={18} className="animate-spin text-blue-600" />
            ) : isLiveConnected ? (
              <MicOff size={18} />
            ) : (
              <Mic size={18} className="text-blue-600" />
            )}
            <span className="hidden sm:inline">{isLiveConnecting ? 'Connecting...' : isLiveConnected ? 'End Voice Session' : 'Voice Mode'}</span>
          </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 overflow-hidden flex flex-col sm:flex-row relative">
        {/* Knowledge Base Sidebar */}
        <div className="hidden sm:flex flex-col w-64 border-r border-slate-200 bg-white p-4 shrink-0 overflow-y-auto shadow-[2px_0_10px_rgba(0,0,0,0.02)]">
          <h2 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 border-b border-slate-100 pb-2">Reference Documents</h2>
          <ul className="space-y-4">
            <li>
              <button onClick={() => downloadReferenceDoc('NEGOTIATED AGREEMENT')} className="flex gap-3 text-sm text-slate-600 items-start text-left hover:text-blue-600 group transition-colors">
                <Download size={16} className="text-blue-500 shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
                <span className="leading-snug">Negotiated Agreement (2024-2027)</span>
              </button>
            </li>
            <li>
              <button onClick={() => downloadReferenceDoc('NURSING ADDITIONAL COMPENSATION MOU')} className="flex gap-3 text-sm text-slate-600 items-start text-left hover:text-blue-600 group transition-colors">
                <Download size={16} className="text-blue-500 shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
                <span className="leading-snug">Nursing MOU (2025-26)</span>
              </button>
            </li>
            <li>
              <button onClick={() => downloadReferenceDoc('HIGH DEMAND/HIGH WAGE ADDITIONAL COMPENSATION MOU')} className="flex gap-3 text-sm text-slate-600 items-start text-left hover:text-blue-600 group transition-colors">
                <Download size={16} className="text-blue-500 shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
                <span className="leading-snug">High Demand MOU (2025-26)</span>
              </button>
            </li>
            <li>
              <button onClick={() => downloadReferenceDoc('DIGITAL ACCESSIBILITY')} className="flex gap-3 text-sm text-slate-600 items-start text-left hover:text-blue-600 group transition-colors">
                <Download size={16} className="text-blue-500 shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
                <span className="leading-snug">Digital Accessibility MOU (2026)</span>
              </button>
            </li>
          </ul>
        </div>

        {/* Chat Area */}
        {isLiveConnected ? (
          <div className="flex-1 flex flex-col items-center justify-center p-8 bg-slate-50 relative overflow-hidden">
             {/* Live UI State */}
             <motion.div 
               initial={{ opacity: 0, scale: 0.9 }}
               animate={{ opacity: 1, scale: 1 }}
               className="flex flex-col items-center gap-8"
             >
                <div className="relative">
                  <motion.div
                    animate={{ scale: [1, 1.2, 1] }}
                    transition={{ repeat: Infinity, duration: 2 }}
                    className="absolute inset-0 bg-blue-400 rounded-full blur-xl opacity-30"
                  />
                  <div className="w-32 h-32 bg-white rounded-full flex items-center justify-center shadow-xl border border-slate-100 relative z-10">
                     <Mic size={48} className="text-blue-600" />
                  </div>
                </div>
                <div className="text-center">
                  <h2 className="text-2xl font-bold tracking-tight text-slate-800 mb-2">Live Voice Mode Active</h2>
                  <p className="text-slate-500 px-4 max-w-md">I am listening. Feel free to ask me anything about the PCFT agreement or your faculty rights.</p>
                </div>
                
                {/* Closed Captioning */}
                <div className="w-full max-w-2xl mt-8">
                  <div className="bg-white/80 backdrop-blur-md border border-slate-200 rounded-2xl shadow-sm h-64 overflow-y-auto p-6 flex flex-col space-y-4">
                    {transcript.length === 0 ? (
                      <div className="flex-1 flex items-center justify-center text-slate-400 italic">
                        Start speaking...
                      </div>
                    ) : (
                      transcript.map((msg, i) => (
                        <div key={i} className="flex">
                          <div className="max-w-[90%]">
                            <p className={`text-base leading-relaxed ${msg.role === 'user' ? 'text-slate-600 font-medium' : 'text-slate-900 font-medium'}`}>
                              <span className="text-[10px] sm:text-xs font-bold uppercase tracking-wider text-slate-400 mr-3 shrink-0">
                                {msg.role === 'user' ? 'You' : 'PCFT Assistant'}
                              </span>
                              <span>{msg.text.trim()}</span>
                            </p>
                          </div>
                        </div>
                      ))
                    )}
                    <div ref={bottomRef} className="h-2" />
                  </div>
                </div>
             </motion.div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col relative overflow-hidden bg-white shadow-inner">
            <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-6">
              <AnimatePresence initial={false}>
                {messages.map((msg, idx) => (
                  <motion.div 
                    key={idx}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} max-w-4xl mx-auto w-full group`}
                  >
                    <div className={`flex gap-3 max-w-[85%] ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                      {msg.role !== 'system' && (
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 shadow-sm transition-transform group-hover:scale-105 ${msg.role === 'user' ? 'bg-slate-800 text-white' : 'bg-blue-600 text-white'}`}>
                          {msg.role === 'user' ? <User size={16} /> : <Bot size={16} />}
                        </div>
                      )}
                      
                      <div className={`rounded-2xl px-5 py-3.5 shadow-sm text-[15px] leading-relaxed ${
                        msg.role === 'user' 
                          ? 'bg-slate-800 text-white rounded-tr-sm' 
                          : msg.role === 'system'
                            ? 'bg-red-50 text-red-800 border border-red-100 rounded-xl w-full text-center'
                            : 'bg-slate-50 text-slate-800 border border-slate-100 rounded-tl-sm prose-slate prose-sm max-w-none'
                      }`}>
                        {msg.role === 'model' ? (
                          <div className="markdown-body custom-md">
                            <Markdown remarkPlugins={[remarkGfm]}>{msg.text}</Markdown>
                          </div>
                        ) : (
                          <p className="whitespace-pre-wrap font-medium">{msg.text}</p>
                        )}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
              
              {isLoading && (
                <motion.div 
                  initial={{ opacity: 0 }} 
                  animate={{ opacity: 1 }}
                  className="flex justify-start max-w-4xl mx-auto w-full"
                >
                  <div className="flex gap-3">
                    <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center shrink-0 text-white shadow-sm">
                      <Bot size={16} />
                    </div>
                    <div className="bg-slate-50 border border-slate-100 rounded-2xl rounded-tl-sm px-5 py-4 shadow-sm flex items-center gap-2">
                       <span className="w-2 h-2 bg-slate-300 rounded-full animate-bounce [animation-delay:-0.3s]"></span>
                       <span className="w-2 h-2 bg-slate-300 rounded-full animate-bounce [animation-delay:-0.15s]"></span>
                       <span className="w-2 h-2 bg-slate-300 rounded-full animate-bounce"></span>
                    </div>
                  </div>
                </motion.div>
              )}
              <div ref={bottomRef} className="h-2" />
            </div>

            <div className="p-4 sm:p-6 bg-white border-t border-slate-100 shadow-[0_-4px_10px_rgba(0,0,0,0.01)]">
              {attachments.length > 0 && (
                <div className="max-w-4xl mx-auto mb-3 flex flex-wrap gap-2">
                  {attachments.map((att, i) => (
                    <div key={i} className="flex items-center gap-2 bg-slate-100 text-slate-700 px-3 py-1.5 rounded-lg text-sm border border-slate-200 shadow-sm">
                      <FileText size={14} className="text-slate-500" />
                      <span className="truncate max-w-[150px]">{att.name}</span>
                      <button 
                        type="button" 
                        onClick={() => setAttachments(prev => prev.filter((_, idx) => idx !== i))}
                        className="hover:text-red-500 transition-colors"
                      >
                        <X size={14} />
                      </button>
                    </div>
                  ))}
                </div>
              )}
              <form onSubmit={handleSend} className="max-w-4xl mx-auto relative flex items-center bg-slate-50 border border-slate-200 rounded-2xl shadow-inner focus-within:ring-2 focus-within:ring-blue-500/50 focus-within:border-blue-500 transition-all">
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="p-3 ml-1 text-slate-400 hover:text-blue-600 transition-colors bg-transparent border-none outline-none"
                  disabled={isLoading}
                  title="Attach file (Image, PDF, TXT)"
                >
                  <Paperclip size={20} />
                </button>
                <input
                  type="file"
                  multiple
                  ref={fileInputRef}
                  onChange={handleFileChange}
                  accept="image/*,application/pdf,text/plain"
                  className="hidden"
                />
                <input
                  type="text"
                  value={inputValue}
                  onChange={e => setInputValue(e.target.value)}
                  onPaste={handlePaste}
                  placeholder="Ask a question or paste an image/file here..."
                  className="w-full bg-transparent text-slate-900 pr-14 py-3.5 focus:outline-none font-medium placeholder:text-slate-400 placeholder:font-normal text-base"
                  disabled={isLoading}
                />
                <button
                  type="submit"
                  disabled={(!inputValue.trim() && attachments.length === 0) || isLoading}
                  className="absolute right-2 p-2.5 bg-blue-600 text-white rounded-full hover:bg-blue-700 disabled:opacity-50 disabled:hover:bg-blue-600 transition-colors shadow-sm"
                >
                  <Send size={18} />
                </button>
              </form>
              <div className="text-center mt-3">
                <p className="text-xs text-slate-400">AI assistants can make mistakes. Please verify important information with PCFT leadership.</p>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
